sudo: required
language: php
dist: trusty

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rabbitmq-server beanstalkd

before_script:
  - git clone --depth=50 --branch=2016.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-mqueue ext/
  - composer require "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"

script:
  - vendor/bin/phing -Ddir=ext/ai-mqueue coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-mqueue/.coveralls.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm