sudo: required
dist: trusty
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes beanstalkd rabbitmq-server=3.5.7-1

before_script:
  - git clone --depth=50 --branch=2018.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-mqueue ext/
  - composer require "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"

script:
  - vendor/bin/phing -Ddir=ext/ai-mqueue coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-mqueue/.coveralls.yml
