sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - git clone --depth=50 --branch=master git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-mqueue ext/
  - composer require "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0"
  - apt-get install -y php5-stomp stompserver rabbitmq-server

script:
  - vendor/bin/phing -Ddir=ext/ai-mqueue setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-mqueue/.coveralls.yml
